//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kpk_schedule.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public Nullable<int> IdGroups { get; set; }
        public Nullable<int> IdSubject { get; set; }
        public Nullable<int> IdCouples { get; set; }
        public Nullable<int> IdCabinet { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    }
}
